### PR TITLE
Make the author more dynamic for posts

### PR DESCRIPTION
**Pull request by benmatselby**
This PR covers:

- Making the author name on a post clickable to their profile.
- Created a `<SocialLink>` component which has some logic in it to render icons (not yet, need some icons) based on a URL.
- Pass `authorProfile` around to make things more dynamic.

After a chit chat with Andy I miss understood the icons on the post page, so they will be sharing icons, not `authorProfile.social`. However, this shows a working example, so we could merge, and then swap out the logic when we understand how that will work.

### CODE REVIEW

**Comment by markgaze** [comment]
#### 📝Changed routes:


| [**/post/\[id\]**](https://somedevsdo-blog-b7285x8do-markgaze.vercel.app/post/[id]) |
|:-:|
|<a href="https://somedevsdo-blog-b7285x8do-markgaze.vercel.app/post/[id]">Screenshot of /post/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/z_48iU0e5EUZZmTcSdTMprC4lq7tBH6ZnVSGNnXdmmfHxS4SQKvydqZd15CxdQM9okFZyqQcpWqxNkSVAi0J5w.png">(view full size)</a> |







Commit e9ac01bae0c301b27a81d287af6c90fc08d6a279 (https://somedevsdo-blog-b7285x8do-markgaze.vercel.app).

**Comment by andrewbarnesweb** [comment]
Looks great! I reckon get it merged for now, and then we can move the icon display to the `/author/[id].tsx` page. 

Looking at the early mock up, Would we want to convert the `json` to `md` to allow authors write their own bios with formatted text? Or would you see it as another property in the json?

image

**Review by andrewbarnesweb — APPROVED** [review]

**Review by andrewbarnesweb — APPROVED** [review]

**Comment by benmatselby** [comment]
I think it's json right up until it can't be and then they can overwrite with a page?

The json drives other aspects of the author features.

**Comment by andrewbarnesweb** [comment]
As in, the author decides when it's JSON vs md? Would it not be a case of swapping the `json` for `front matter`?

**Comment by benmatselby** [comment]
> As in, the author decides when it's JSON vs md? Would it not be a case of swapping the `json` for `front matter`?

We can do that, however I would have thought that was harder? Loading a markdown file to parse front matter for everything but their blurb. I may be misunderstanding this. JSON allows us to have a neat config file per person, imo. It's easier to work with.

**Comment by andrewbarnesweb** [comment]
Agree. But if someone wants formatted text in their bio with links and paragraphs. Just add the HTML into a JSON property? Something simple like the following? We'd also need to ensure that all authors wrap their bio in a para if we went that route?

JSON a load cleaner if we want to just limit authors to a basic paragraph about themselves. Just wanted the page to sell the person, and a paragraph might be limiting.

```html
<p>Lorem Ipsum is simply dummy text of the printing and 
<a href="https://en.wikipedia.org/wiki/Typesetting">typesetting industry</a>. 
Lorem Ipsum has been the <strong>industry's standard dummy text ever since the 1500s</strong>, 
when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>

<p>It has survived not only five centuries, <em>but</em> also the leap into electronic typesetting, 
remaining essentially unchanged.</p>
```

**Comment by benmatselby** [comment]
I'd need to double check this, but wouldn't you then just drop in a file:

```
pages/author/andy.tsx
```

Which then overrides the `[id].tsx` file? Then the author is free to do as they please. I think we are trying to solve two problems with a single solution:

- Configuration about authors.
- A biography page.

I believe that JSON solves the first point, and an author page solves the second. Personally my bio won't have links, as it will either be the bio on my homepage, or a cut down version of my about page on my personal site. The config file already has the social links I'd like to be echoed out.

If we provide two solutions, engineers/authors can pick the flavour they want, without providing a higher bar to entry, or restricting that can be done. If I went with JSON and added a one or two line bio, I get the standard author page design we build. If you want to go all in, then you can go the next step further.

**Comment by andrewbarnesweb** [comment]
Coolio. Let's see how it pans out and what sort of middle ground we can get to. Don't want to go down this line... 

> Then the author is free to do as they please.

It should be consistent, with the same layout and highlighting recent posts etc.

**Comment by davidn0rman** [comment]
> It should be consistent, with the same layout and highlighting recent posts etc.

Agreed. For me, at least.

**Comment by andrewbarnesweb** [comment]
God knows what Cowling's would be like. Imagining some sort of Dating profile 😂 .

**Pull request merged**
