### PR TITLE
Add the "og" meta data

### PR DESCRIPTION
**Pull request by benmatselby**
I think we are going to need a URL config item to prefix the image and
the URL, but for now it's a start.

### CODE REVIEW

**Comment by markgaze** [comment]
#### 📝Changed routes:


| [**/post/\[id\]**](https://somedevsdo-blog-a036gzo87-markgaze.vercel.app/post/[id]) |
|:-:|
|<a href="https://somedevsdo-blog-a036gzo87-markgaze.vercel.app/post/[id]">Screenshot of /post/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/9v_UhPmGMVEFxq85677_gcpp8cPY-Ki0jsYp3l32nXmOrDdj-31o3IvSVw_PEWVtAgBnqXihYUsu_ITqMKYkkw.png">(view full size)</a> |







Commit 191b88cc2fdc729d3c79f7bcad47dcfbba90f964 (https://somedevsdo-blog-a036gzo87-markgaze.vercel.app).

**Comment by benmatselby** [comment]
Screenshot 2021-05-26 at 21 57 24

We need to get a env file for the different URLS to prefix the card content.

**Comment by andrewbarnesweb** [comment]
What's the config to keep it like this? I prefer the styling here: 
image

Was hoping we could work out something like this... 
image

**Comment by andrewbarnesweb** [comment]
I don't know anything about this stuff by the way. Just looked at Vercel's, and seems to be a self hosted image that takes parameters to create the image 😬 .

- https://og-image.vercel.app/This%20could%20be%20the%20start%20of%20something%20new.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.zeit.co%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg
- https://opengraph.githubassets.com/9cd1ee0ed0262b1a141f38c9717e0f0f4c59e479da9c75145cb2c9c93eb543d5/andrewbarnesweb/andrew-barnes-portfolio

**Comment by andrewbarnesweb** [comment]
In the short term, is it this param that gives us a large, more impactful featured image? 

image 

image

**Comment by andrewbarnesweb** [comment]
https://flaviocopes.com/canvas-node-generate-image/ this seems like the thing. If we get this merged, then I'll raise an issue to see how practical it is 👍🏻

**Comment by benmatselby** [comment]
@andrewbarnesweb Happy for this to be merged, or closed. It was what I had on my personal blog, but not precious. We need to get that env var thing added as per Mark's comments too.

**Comment by andrewbarnesweb** [comment]
Something is better than nothing. We can refine as we go 👌🏻

**Review by andrewbarnesweb — APPROVED** [review]

**Pull request merged**
